name: Build and Push Test Images

on:
  workflow_dispatch:
    inputs:
      build-target:
        description: Build Target
        required: true
        default: "+test"
        type: choice
        options:
          - "+test"
          - "+all"
      zwave-js-version:
        description: Z-Wave JS version
        required: true
      zwave-js-server-version:
        description: Z-Wave JS Server version
        required: true
      npm-install-flags:
        description: Extra `npm install` flags
        required: false
        type: string
      push:
        description: Push image to registries
        required: true
        default: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install earthly
        uses: earthly/actions-setup@v1.0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Images
        run: earthly --use-inline-cache --no-output --strict ${{ github.event.inputs.build-target }} --ZWAVE_JS_VERSION=${{ github.event.inputs.zwave-js-version }} --ZWAVE_JS_SERVER_VERSION=${{ github.event.inputs.zwave-js-server-version }} --NPM_INSTALL_EXTRA_FLAGS=${{ github.event.inputs.npm-install-flags }}

      - name: Push to Docker Hub
        if: github.event.inputs.push == 'true' && github.event.inputs.build-target == '+all'
        run: earthly --use-inline-cache --no-output --strict --push ${{ github.event.inputs.build-target }} --ZWAVE_JS_VERSION=${{ github.event.inputs.zwave-js-version }} --ZWAVE_JS_SERVER_VERSION=${{ github.event.inputs.zwave-js-server-version }} --NPM_INSTALL_EXTRA_FLAGS=${{ github.event.inputs.npm-install-flags }}

      - name: Push to GitHub Container Registry
        if: github.event.inputs.push == 'true' && github.event.inputs.build-target == '+all'
        run: earthly --use-inline-cache --no-output --strict --push ${{ github.event.inputs.build-target }} --REGISTRY=ghcr.io --ZWAVE_JS_VERSION=${{ github.event.inputs.zwave-js-version }} --ZWAVE_JS_SERVER_VERSION=${{ github.event.inputs.zwave-js-server-version }} --NPM_INSTALL_EXTRA_FLAGS=${{ github.event.inputs.npm-install-flags }}

      - name: Push to GitHub Container Registry
        if: github.event.inputs.push == 'true' && github.event.inputs.build-target == '+test'
        run: earthly --use-inline-cache --no-output --strict --push ${{ github.event.inputs.build-target }} --REGISTRY=ghcr.io --REPOSITORY=${{ secrets.TEST_REPO }} --ZWAVE_JS_VERSION=${{ github.event.inputs.zwave-js-version }} --ZWAVE_JS_SERVER_VERSION=${{ github.event.inputs.zwave-js-server-version }} --NPM_INSTALL_EXTRA_FLAGS=${{ github.event.inputs.npm-install-flags }}
