name: Build and Release Images

on:
  push:
    branches:
      - main
    paths:
      - .arg
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      build-target:
        description: Build Target
        required: false
        default: "+test"
        type: choice
        options:
          - "+test"
          - "+all"
      zwave-js-version:
        description: Z-Wave JS version
        required: false
        default: "latest"
      zwave-js-server-version:
        description: Z-Wave JS Server version
        required: false
        default: "latest"
      npm-install-flags:
        description: Extra `npm install` flags
        required: false
        type: string
      push:
        description: Push image to registries
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install earthbuild
        uses: EarthBuild/actions-setup@f4d20223e70dbb43b5fc08c4d857ab9cf0dbf3ae # v2.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set workflow dispatch environment
        if: github.event_name == 'workflow_dispatch'
        run: |
          zjsver=${{ github.event.inputs.zwave-js-version }}
          zjssver=${{ github.event.inputs.zwave-js-server-version }}
          npmflags=${{ github.event.inputs.npm-install-flags }}
          printf 'EARTHLY_BUILD_ARGS=ZWAVE_JS_VERSION=%s,ZWAVE_JS_SERVER_VERSION=%s,NPM_INSTALL_EXTRA_FLAGS=%s\n' "${zjsver}" "${zjssver}" "${npmflags}" >> "${GITHUB_ENV}"
          printf 'target=%s\n' "${{ github.event.inputs.build-target }}" >> "${GITHUB_ENV}"

      - name: Set PR environment
        if: github.event_name == 'pull_request'
        run: |
          printf 'target=+test\n' >> $GITHUB_ENV

      - name: Set release environment
        if: github.event_name == 'push'
        run: |
          printf 'target=+all\n' >> $GITHUB_ENV

      - name: Build Images
        run: earth --ci ${{ env.target }}

      - name: Push to Docker Hub
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push == 'true')
        run: earth --ci --push ${{ env.target }}

      - name: Push to GitHub Container Registry
        if: github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push == 'true')
        run: earth --ci --push ${{ env.target }} --REGISTRY=ghcr.io
